name = "TreeOfLife"
uuid = "84ef9827-9357-47d4-b4e4-19dbb3edd7c1"
authors = ["Yu-Chang YANG <yang.yc.allium@gmail.com>"]
version = "0.0.3"

[deps]
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
